#!/bin/bash

varhostname="$(curl http://169.254.169.254/latest/meta-data/hostname)"
varipv4="$(curl http://169.254.169.254/latest/meta-data/public-ipv4)"
vardate=$(date +"%d/%m/%Y %H:%M:%S:%N")



echo $vardate=hostname=$varhostname >> /properties/deploy.properties
echo $vardate=ipv4=$varipv4 >> /properties/deploy.properties
echo $vardate=deploydate=$vardate >> /properties/deploy.properties